1주차 미션 제출(김현빈)
christianB053/frontend-mission pull request #1
Opened 2022-01-09 11:41 UTC by christianB053

# 1주차 미션 제출(김현빈)

## 접근 방법

* [ ] 미션 코드를 구현하기 위해서 어떤 생각들을 했는지 정리해보세요.
  ->  코드 작성은 강의를 들으며 따라 해 본 것이 전부였고, 스스로 작성해 본 적은 이번이 처음이라 미션을 이해하고 나서도
구현해 낼 수 있는 방법은 알지 못해 우선 강의와 검색을 통해 비슷한 코드들을 찾아야겠다 라는 생각으로 시작했습니다. 
2주차에는 좀 더 체계적으로 TDD 방법론에 따라 생각해 보고 작성하는 것이 목표입니다.

## 특이사항

* [ ] 구현하면서 궁금했던 점이나, 아쉬웠던 부분이 있으면 적어주세요.
  -> 온갖 단어를 조합해 보며 검색을 시도했지만 알아내지 못했던 문자열을 왼쪽으로 한 칸씩 회전시키는 방법과 경고창에 2가지 이상 함수를 호출할 수 있는 방법이 너무 궁금합니다.

## 제출 후 확인

* [ ] 본인의 구현 결과를 `dev` 브랜치에 구현하고, `dev` 브랜치에서 `submission` 브랜치로 PR을 보내주세요.
* [ ] Pull Request 생성 후 Reivewer에 @externship-master 와 @lkaybob 을 추가해주세요.

2022-01-10 04:30 UTC, jambottle requested changes
현빈님, 안녕하세요? 같은 그룹으로 배정된 김재원이라고 합니다 😃

혹시 제가 남긴 리뷰에 관해서 궁금한 점 있으면 댓글 남겨주세요!
첫 미션부터 고생 많으셨습니다, 앞으로도 파이팅!!

2022-01-10 04:30 UTC, jambottle commented on mission/src/views/Home.vue
> +        .join('');
현빈님, 문자열 회전시키는 방법에 대해서 고민 많으셨을 것 같아요.
`"Project Lion".split('').splice(1).join('');`과 같이 구현하신 메서드의 결과를 실제 문자열에 적용해 보면,

1. 문자열을 한 글자씩 쪼개 배열로 만들고(`split('')`),
2. 문자열이 한 글자씩 쪼개진 배열에서 첫 번째 요소인 "P"를 삭제한 다음에(`splice(1)`),
3. 다시 배열의 모든 요소를 문자열로 합치는(`join('')`) 동작인 걸 확인하실 수 있을 거에요. (⇒ **결과**: "roject Lion")

그럼 앞서 삭제했던 첫 번째 요소 "P"를 위에서 나온 결과 뒤에 붙여주면 되지 않을까요? 🤔

2022-01-10 04:30 UTC, jambottle commented on mission/src/views/Home.vue
> +        .join('');
보통 저는 메서드(함수)를 구현하면서 그때그때 결과값을 `console.log()`로 확인해보면서 진행하는 편인데요-

이번 미션에서 제시된 **TDD 방법론**에 따라 기대값과 실제 결과값을 비교하는 테스트 코드를 작성하고,
이 테스트를 반복 실행함으로써 요구사항을 향해 메서드를 수정해나가는 것도 또 하나의 방법이 되겠다는 생각이 듭니다!

2022-01-10 04:30 UTC, jambottle commented on mission/src/views/Home.vue
> +      this.counterMessage();
맨 아래의 `alertButton`이 실행되었을 때, `alertMessage`와 `counterMessage`에 의해 알림창이 두 번 연속 뜰 것 같네요.

요구 사항에 따르면, **하나의 알림창에 `message`와 `counter`가 동시에 보여져야 하기 때문에...**
구현하신 코드들을 바탕으로 아래의 두 가지 방법 중 하나를 선택해 조금 더 수정해보시는 건 어떨까요?

1. `alert()` 함수 안에 두 개의 데이터를 동시에 표시하는 방법 (**🔍참고**: JavaScript 템플릿 리터럴)
2. `alert()` 함수를 이용하지 않고, 새로운 모달 컴포넌트로 알림창을 대체하는 방법 (**🔍참고**: Vue.js 콧수염 괄호)

2022-01-10 08:00 UTC, allegoryj commented on mission/public/index.html
> +    <title><1st mission></title>
타이틀을 고치는 이런 기본적인 부분이 어떻게 보면 가장 중요한 부분일 아닐까라는 생각이 듭니다. 세심하게 신경 쓰시는 부분이 좋았습니다.

2022-01-10 08:04 UTC, allegoryj commented
안녕하세요 현빈님! 2그룹 정진재입니다.
미션 수행하시느라 정말 고생 많으셨을 것 같아요.
저도 이제 막 배우는 단계라 부족한 점이 많은데 같이 파이팅 하셔서 TDD도 배우고
함께 성장해 나가면 좋을 것 같습니다. 앞으로도 잘 부탁드립니다:)

2022-01-10 09:40 UTC, jambottle commented on mission/src/views/Home.vue
> +      this.counterMessage();
현빈님, `템플릿 리터럴`을 적용할 때에는 일반 따옴표를 쓰는 것이 아니라 **백틱(``)이라는 문자로 감싸주어야 해요!**
그래야 백틱 사이에 있는 `${ }`가 정상적으로 작동합니다. 링크 하나 남겨드리니 일반 따옴표를 썼을 때와 차이점을 확인해보셔요-

> 참고로... 아래 자료 보시면 아시겠지만, 꼭 템플릿 리터럴을 사용하지 않더라도 일반 따옴표로 같은 기능을 구현할 수 있긴 합니다.
> 혹시 제가 드린 피드백으로 인해 혼란스러우셨다면 죄송해요 ^^;; 일반 따옴표와 연산자로도 충분히 구현할 수 있습니다!!

**🔍참고**: https://poiemaweb.com/es6-template-literals

2022-01-10 10:49 UTC, ddukddak-kim commented
현빈님 안녕하세요 :) 
이번 익스텐션 기간동안 Peer 리뷰를 함께 할 2 그룹 김경민 입니다. 
만나서 반가워요 😎

이번 주 미션 수행하느라 고생 많으셨습니다-!

2022-01-10 12:04 UTC, Soohyeon02 commented
안녕하세요 현빈님 이번에 같은 조로 배정된 황수현입니다!
아직 부족한 점이 많지만 같이 열심히 미션 수행했으면 좋겠습니다.
미션 수행하느라 수고 많으셨습니다!

2022-01-10 13:41 UTC, KyubumJang commented on mission/src/views/Home.vue
> +      this.counterMessage();
아주 좋은 코멘트 남겨주신 것 같습니다.

2022-01-10 13:46 UTC, KyubumJang commented
안녕하세요. 현빈님! 같은 그룹2로 배정된 장규범입니다.
이번에 구현하시면서 고민도 많이 하시고 개발하기 위해서 여러 키워드로 많이 찾아보신 것 같아요! 열심히 같이 미션 수행해나가요! 이번주 수고 많으셨습니다.👍
앞으로 잘 부탁드립니다!😊

2022-01-12 10:12 UTC, merged

2022-01-14 08:50 UTC, jambottle commented on mission/src/components/Mission.vue
> +      alert(`${this.inputText} ${this.counter}`);
👍👍